# Generated by Django 3.2.10 on 2023-12-13 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Dedline',
            new_name='Deadline',
        ),
    ]
